[project]
name = "odoo-addons-sygel-technology-sy-credit-control"
version = "16.0.20241105.0"
dependencies = [
    "odoo-addon-account_invoice_overdue_warn_public>=16.0dev,<16.1dev",
    "odoo-addon-account_invoice_overdue_warn_sale_public>=16.0dev,<16.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 16.0",
]
